"""Unique names and nullable charging_station_id in Connector

Revision ID: 4577f3b767f2
Revises: 9745675d7c13
Create Date: 2024-04-11 21:14:39.261357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4577f3b767f2'
down_revision: Union[str, None] = '9745675d7c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'charging_stations', ['name'])
    op.alter_column('connectors', 'charging_station_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'connectors', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connectors', type_='unique')
    op.alter_column('connectors', 'charging_station_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'charging_stations', type_='unique')
    # ### end Alembic commands ###
