"""Initial migration

Revision ID: 9745675d7c13
Revises: 
Create Date: 2024-04-11 20:09:15.430176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9745675d7c13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_station_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plug_count', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('current_type', sa.Enum('AC', 'DC', name='currenttypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('charging_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('firmware_version', sa.String(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['charging_station_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('charging_station_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charging_station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connectors')
    op.drop_table('charging_stations')
    op.drop_table('charging_station_types')
    # ### end Alembic commands ###
